name: CI App Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate-app:
    name: Validate App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@10.30.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "./app/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Astro check
        run: pnpm check

      - name: Build project
        run: pnpm build
