name: test-oidc

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::320789259849:role/github-oidc-deploy-portfolio
          aws-region: sa-east-1

      - name: Test AWS identity
        run: aws sts get-caller-identity